export const STATUS_PROCESSO = {
  EM_ANDAMENTO: 'Em andamento',
  PRAZO_PROXIMO: 'Prazo próximo',
  RESPONDIDO: 'Respondido',
  CONCLUIDO: 'Concluído',
  ENCERRADO: 'Encerrado',
  EXPIRADO: 'Expirado',
} as const

export type StatusProcesso = typeof STATUS_PROCESSO[keyof typeof STATUS_PROCESSO]

export const STATUS_PROCESSO_FILTROS = [
  STATUS_PROCESSO.EM_ANDAMENTO,
  STATUS_PROCESSO.PRAZO_PROXIMO,
  STATUS_PROCESSO.RESPONDIDO,
  STATUS_PROCESSO.CONCLUIDO,
  STATUS_PROCESSO.ENCERRADO,
  STATUS_PROCESSO.EXPIRADO,
] as const

export const STATUS_PROCESSO_SUGESTOES = [
  STATUS_PROCESSO.EM_ANDAMENTO,
  STATUS_PROCESSO.PRAZO_PROXIMO,
  STATUS_PROCESSO.RESPONDIDO,
  STATUS_PROCESSO.CONCLUIDO,
  STATUS_PROCESSO.ENCERRADO,
  STATUS_PROCESSO.EXPIRADO,
] as const
